### PR TITLE
[1] Fix IE11 issue [2] Prepend `data-`

### PR DESCRIPTION
**Pull request by kyooriouskoala**
[1] Fix IE11 issue where custom attribute needs value or it won't be added
[2] Prepend custom attribute with `data-` to follow general practice

### CODE REVIEW

**Comment by jonathantneal** [comment]
Hi @kyooriouskoala,

Thanks for checking out the library and diving into how it works. I love that.

Many libraries that include a dash in an assigned attribute do not prepend data, so I can’t agree that it’s general practice. Here are some examples and additional discussion on the issue:

- https://angular.io/guide/attribute-directives
- https://vuejs.org/v2/guide/syntax.html#Attributes
- https://github.com/whatwg/html/issues/2271

Secondly, I’m using this library in IE11 without issue, and while `setAttribute` does need a value, an empty string counts as such a value. Here’s the guidance from MDN:

> Boolean attributes are considered to be true if they're present on the element at all, regardless of their actual value; **as a rule, you should specify the empty string ("") in value (some people use the attribute's name; this works but is non-standard)**.
> — [MDN Element.setAttribute()](https://developer.mozilla.org/en-US/docs/Web/API/Element/setAttribute) (the emphasis was mine)

---

For the purpose of keeping this issue open or closed, were you experiencing any issues?

I’m so glad someone dived into the code. I worry with how much open source I maintain that too many folks might use it like a _black box_. I also welcome your challenges as well as other challenges to the coding choices I’ve made. Thanks again for taking a deeper look and for writing such a clear and descriptive PR.

**Comment by kyooriouskoala** [comment]
Hi @jonathantneal,

### `data-` prefix
I suppose general practice is pretty subjective. Each time I work on a new project, I would usually check on the “latest general/common best” practices. 

I had read discussions about whether or not to prefix custom attribute with `data-` but those were not related to any framework usage since most of the work I had done in the past were static sites. Thanks for sharing those discussion links, I have just read them. 

For custom attribute, I am aware that some attribute do not prepend data and hence having the `data-` prefix doesn’t quite make sense. However, I agree with the thoughts and considerations that been put out there that say something along this line: 
1. To avoid conflicts that could be defined in [HTML attributes](https://developer.mozilla.org/en-US/docs/Web/HTML/Attributes)
2. The `data-` prefix provides clear indication that it’s a custom attribute.

I recently started learning Vue and I am not familiar with other frameworks; pardon the lack of terminology and poor articulation. 

So far, I have not found myself needing to use custom non-data attribute. As for data attribute, I had never actually thought about prefixing custom attribute with `data-` since I have been trying to do things the Vue way (e.g. avoid DOM manipulation whenever possible) and that I don’t feel the need to have it rendered in HTML.

Thinking about it now, I would still prefix it with `data-` if there’s a decision to render the custom attributes in HTML.

Have you used this library with Vue? If you have, how did you use it? 

### IE11

My bad. I only checked whether the `keyboard-focus` attribute gets rendered in the HTML. While the attribute doesn’t appear on this version of IE (Windows 10), the style still works. 
￼
image


### Suggestion
Have you thought and/or considered to accept the attribute name as argument to allow more flexibility for the user?

**Comment by kyooriouskoala** [comment]
Hi @jonathantneal, any chance you'd be sharing more of your thoughts? If not, feel free to close this. Thanks.

**Comment by jonathantneal** [comment]
Yes, I think the attribute should be configurable. I never saw these updates, and I’m really sorry about that. I am closing the PR, but I’m open to a new one that makes the attribute configurable. Thank you for your diligence and quality feedback, @kyooriouskoala.

**Pull request closed without merging**
